# Generated by Django 5.1.4 on 2025-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='isShopkeeper',
            field=models.BooleanField(default=True),
        ),
    ]
