# Generated by Django 5.1.4 on 2025-01-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shopkeeper_isshopkeeper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='isShopkeeper',
        ),
        migrations.AddField(
            model_name='myuser',
            name='isShopkeeper',
            field=models.BooleanField(default=False),
        ),
    ]
