# Generated by Django 5.1.4 on 2025-01-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cartitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carts',
            name='payment_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
