# Generated by Django 5.1.4 on 2025-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_carts_order_id_carts_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='payment_signature',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
