# Generated by Django 5.1.4 on 2025-01-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproducts',
            name='delivery_price',
            field=models.FloatField(default=0),
        ),
    ]
